# -------------------------------
# Authentication API - HTTP Requests
# -------------------------------

### Register a user (POST /api/register)
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "emailAddress": "test@example.com",
  "password": "V7fR9pQ2"
}

### Authenticate as an CUSTOMER (POST /api/auth)
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "emailAddress": "test@example.com",
  "password": "V7fR9pQ2"
}

> {% client.global.set("bearerToken", response.body.token) %}

### Authenticate as an ADMIN (POST /api/auth)
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "emailAddress": "admin@example.com",
  "password": "V7fR9pQ2"
}

> {% client.global.set("bearerToken", response.body.token) %}

# -------------------------------
# Customers API - HTTP Requests
# -------------------------------

### Get the logged-in customer (GET /api/customers/me)
GET http://localhost:8080/api/customers/me
Authorization: Bearer {{bearerToken}}

> {% client.global.set("customerId", response.body.customerId) %}

### Get all customers (GET /api/customers)
GET http://localhost:8080/api/customers
Authorization: Bearer {{bearerToken}}

### Get a customer by ID (GET /api/customers/{customerId})
GET http://localhost:8080/api/customers/{{customerId}}
Authorization: Bearer {{bearerToken}}

### Update a customer by ID (PUT /api/customers/{customerId})
PUT http://localhost:8080/api/customers/{{customerId}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "firstName": "Johnny",
  "lastName": "Doe",
  "birthDate": "1990-01-01",
  "address": {
    "country": "HUNGARY",
    "city": "Budapest",
    "postalCode": 1007,
    "streetAddress": "Wolf street 15"
  },
  "gender": "MALE",
  "emailAddress": "test@example.com"
}

### Get all customers with query parameters (GET /api/customers)
GET http://localhost:8080/api/customers?birthDateFrom=1990-01-01&birthDateTo=1990-01-01&gender=MALE&emailAddress=johnny.doe@test.com
Authorization: Bearer {{bearerToken}}

### Delete a customer by ID (DELETE /api/customers/{customerId})
DELETE http://localhost:8080/api/customers/{{customerId}}
Authorization: Bearer {{bearerToken}}
