# -------------------------------
# Authentication API - HTTP Requests
# -------------------------------

### Register a user (POST /api/register)
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "emailAddress": "john.doe@test.com",
  "password": "V7fR9pQ2"
}

### Authenticate a user (POST /api/auth)
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "emailAddress": "john.doe@test.com",
  "password": "V7fR9pQ2"
}

> {% client.global.set("bearerToken", response.body.token) %}

# -------------------------------
# Customers API - HTTP Requests
# -------------------------------

### Get all customers (GET /api/customers)
GET http://localhost:8080/api/customers
Authorization: Bearer {{bearerToken}}

### Get all customers with query parameters
GET http://localhost:8080/api/customers?birthDateFrom=1980-01-01&birthDateTo=2000-12-31&gender=MALE&emailAddress=john.doe@test.com
Authorization: Bearer {{bearerToken}}

### Get the logged-in customer (GET /api/customers/me)
GET http://localhost:8080/api/customers/me
Authorization: Bearer {{bearerToken}}
