# -------------------------------
# Authentication API - HTTP Requests
# -------------------------------

### Register a user (POST /api/register)
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "emailAddress": "test@example.com",
  "password": "V7fR9pQ2"
}

### Authenticate as an CUSTOMER (POST /api/auth)
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "emailAddress": "test@example.com",
  "password": "V7fR9pQ2"
}

> {%
    client.global.set("bearerToken", response.body.token)
%}

### Authenticate as an ADMIN (POST /api/auth)
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "emailAddress": "admin@example.com",
  "password": "V7fR9pQ2"
}

> {%
    client.global.set("bearerToken", response.body.token)
%}

# -------------------------------
# Customers API - HTTP Requests
# -------------------------------

### Get the logged-in customer (GET /api/customers/me)
GET http://localhost:8080/api/customers/me
Authorization: Bearer {{bearerToken}}

> {%
    client.global.set("customerId", response.body.customerId)
%}

### Get all customers (GET /api/customers)
GET http://localhost:8080/api/customers
Authorization: Bearer {{bearerToken}}

### Get a customer by ID (GET /api/customers/{customerId})
GET http://localhost:8080/api/customers/{{customerId}}
Authorization: Bearer {{bearerToken}}

### Update a customer by ID (PATCH /api/customers/{customerId})
PATCH http://localhost:8080/api/customers/{{customerId}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "firstName": "Johnny",
  "lastName": "Doe",
  "birthDate": "1990-01-01",
  "address": {
    "country": "HUNGARY",
    "city": "Budapest",
    "postalCode": 1007,
    "streetAddress": "Wolf street 15"
  },
  "gender": "MALE"
}

### Get all customers with query parameters (GET /api/customers)
GET http://localhost:8080/api/customers?birthDateFrom=1990-01-01&birthDateTo=1990-01-01&gender=MALE&
    emailAddress=johnny.doe@test.com
Authorization: Bearer {{bearerToken}}

### Delete a customer by ID (DELETE /api/customers/{customerId})
DELETE http://localhost:8080/api/customers/{{customerId}}
Authorization: Bearer {{bearerToken}}


# -------------------------------
# Products API - HTTP Requests
# -------------------------------

### Get all products (GET /api/products)
GET http://localhost:8080/api/products
Authorization: Bearer {{bearerToken}}

### Create a product (POST /api/products) - Only ADMIN can access this endpoint
POST http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Gaming Laptop",
  "description": "High performance laptop with NVIDIA RTX graphics and 16GB RAM",
  "price": {
    "amount": "599999.00",
    "currency": "HUF"
  }
}

> {%
    const location = response.headers.valueOf("Location");
    const productId = location.substring(location.lastIndexOf("/") + 1);
    client.global.set("productId", productId);
%}

### Query product by ID (earlier created one)
GET http://localhost:8080/api/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}


# -------------------------------
# Basket API - HTTP Requests
# -------------------------------

### Create a basket (POST /api/baskets)
POST http://localhost:8080/api/baskets
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "customerId": "{{customerId}}"
}

> {%
    client.global.set("basketId", response.body.id);
%}

### Add item to basket (POST /api/baskets/{basketId}/items)
POST http://localhost:8080/api/baskets/{{basketId}}/items
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "productId": "550e8400-e29b-41d4-a716-446655440001",
  "quantity": 1,
  "price": {
    "amount": "24.99",
    "currency": "EUR"
  }
}

### Checkout basket (POST /api/baskets/{customerId}/checkout)
POST http://localhost:8080/api/baskets/{{customerId}}/checkout
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

> {%
    client.global.set("checkoutCustomerId", response.body.customerId);
    client.global.set("checkoutItems", response.body.items);
%}


# -------------------------------
# Orders API - HTTP Requests
# -------------------------------

### Create an Order from checked-out basket (POST /api/orders)
POST http://localhost:8080/api/orders
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "customerId": "{{checkoutCustomerId}}",
  "products": [{{checkoutItems}}]
}

> {%
    client.global.set("orderId", response.body.id);
%}

### Get the created order by ID (GET /api/orders/{orderId})
GET http://localhost:8080/api/orders/{{orderId}}
Authorization: Bearer {{bearerToken}}

### Pay for the Order (POST /api/orders/{orderId}/pay)
POST http://localhost:8080/api/orders/{{orderId}}/pay
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "orderId": "{{orderId}}"
}

> {%
    client.global.set("paymentUrl", response.body.paymentUrl);
%}

### Change order Status to SHIPPED (PATCH /api/orders/{orderId}/status)
PATCH http://localhost:8080/api/orders/{{orderId}}/status
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "orderId": "{{orderId}}",
  "newStatus": "SHIPPED"
}

### Cancels an order (POST /api/orders/{orderId}/cancel)
POST http://localhost:8080/api/orders/{{orderId}}/cancel
Content-Type: application/json
Authorization: Bearer {{bearerToken}}